<?php

namespace Database\Seeders;

use App\Models\Domain;
use App\Models\Partner;
use App\Models\Project;
use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $projects = [
            [
                'slug' => 'ponts-kasandjala-i-et-ii',
                'domain' => 'logistique',                       // ← slug du domaine (pas domain_id)
                'title' => [
                    'fr' => 'Construction des ponts KASANDJALA I et II à Sebele',
                    'en' => 'Construction of the KASANDJALA I and II bridges in Sebele',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Sebele, Fizi',
                'start_date' => '2007-01-01',
                'end_date' => '2007-05-01',
                'objectives' => [
                    'fr' => 'Désenclaver la zone et faciliter la circulation des populations.',
                    'en' => 'Open up the area and facilitate the movement of people.',
                ],
                'beneficiaries' => [
                    'fr' => '15 800 personnes',
                    'en' => '15,800 people',
                ],
                'results' => [
                    'fr' => 'Deux ponts construits et mis en service.',
                    'en' => 'Two bridges built and commissioned.',
                ],
                'budget_amount' => 104918.00,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 15800,
                'beneficiaries_unit' => 'personnes',
                'is_featured' => true,
                'published_at' => '2007-05-01 00:00:00',
                'partners' => [
                    'PNUD' => 'funder',
                ],
            ],
            [
                'slug' => 'eau-potable-sebele-fizi',
                'domain' => 'wash',
                'title' => [
                    'fr' => 'Approvisionnement en eau potable et promotion de l\'hygiène à Sebele (Fizi)',
                    'en' => 'Drinking water supply and hygiene promotion in Sebele (Fizi)',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Sebele, Fizi',
                'start_date' => '2008-01-01',
                'end_date' => '2008-11-01',
                'objectives' => [
                    'fr' => 'Lutter contre les maladies d\'origine hydrique et améliorer l\'accès à l\'eau potable.',
                    'en' => 'Fight waterborne diseases and improve access to drinking water.',
                ],
                'beneficiaries' => [
                    'fr' => '22 000 personnes',
                    'en' => '22,000 people',
                ],
                'results' => [
                    'fr' => 'Approvisionnement en eau et promotion de l\'hygiène réalisés.',
                    'en' => 'Water supply and hygiene promotion completed.',
                ],
                'budget_amount' => 124985.00,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 22000,
                'beneficiaries_unit' => 'personnes',
                'is_featured' => false,
                'published_at' => '2008-11-01 00:00:00',
                'partners' => [
                    'Pooled Fund' => 'funder',
                ],
            ],
            [
                'slug' => 'forages-latrines-fizi',
                'domain' => 'wash',
                'title' => [
                    'fr' => 'Forages de 8 puits et assainissement à Fizi',
                    'en' => 'Drilling of 8 wells and sanitation in Fizi',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Fizi',
                'start_date' => '2009-01-01',
                'end_date' => '2009-07-01',
                'objectives' => [
                    'fr' => 'Réduire les maladies d\'origine hydrique et lutter contre le choléra.',
                    'en' => 'Reduce waterborne diseases and fight cholera.',
                ],
                'beneficiaries' => [
                    'fr' => '45 250 personnes',
                    'en' => '45,250 people',
                ],
                'results' => [
                    'fr' => 'Huit puits forés et ouvrages d\'assainissement réalisés.',
                    'en' => 'Eight wells drilled and sanitation works completed.',
                ],
                'budget_amount' => 110079.00,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 45250,
                'beneficiaries_unit' => 'personnes',
                'is_featured' => false,
                'published_at' => '2009-07-01 00:00:00',
                'partners' => [
                    'PNUD' => 'funder',
                ],
            ],
            [
                'slug' => 'route-sebele-kazimia',
                'domain' => 'logistique',
                'title' => [
                    'fr' => 'Réhabilitation de la route SEBELE – KAZIMIA',
                    'en' => 'Rehabilitation of the SEBELE – KAZIMIA road',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Fizi',
                'start_date' => '2010-01-01',
                'end_date' => '2011-01-01',
                'objectives' => [
                    'fr' => 'Réduire le désenclavement et permettre le rapatriement des réfugiés de Tanzanie.',
                    'en' => 'Reduce isolation and enable the repatriation of refugees from Tanzania.',
                ],
                'beneficiaries' => [
                    'fr' => '120 jeunes et 346 ménages',
                    'en' => '120 young people and 346 households',
                ],
                'results' => [
                    'fr' => 'Route réhabilitée et circulable par les ONG humanitaires.',
                    'en' => 'Road rehabilitated and usable by humanitarian NGOs.',
                ],
                'budget_amount' => 180500.00,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 466,
                'beneficiaries_unit' => 'bénéficiaires',
                'is_featured' => false,
                'published_at' => '2011-01-01 00:00:00',
                'partners' => [
                    'PNUD' => 'funder',
                ],
            ],
            [
                'slug' => 'latrines-familiales-sud-kivu',
                'domain' => 'wash',
                'title' => [
                    'fr' => 'Construction de 346 latrines familiales au Sud-Kivu',
                    'en' => 'Construction of 346 family latrines in South Kivu',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Sud-Kivu',
                'start_date' => '2013-01-01',
                'end_date' => '2013-07-01',
                'objectives' => [
                    'fr' => 'Lutter contre l\'insalubrité et les maladies d\'origine hydrique.',
                    'en' => 'Fight unsanitary conditions and waterborne diseases.',
                ],
                'beneficiaries' => [
                    'fr' => '250 filles et garçons',
                    'en' => '250 girls and boys',
                ],
                'results' => [
                    'fr' => '346 latrines familiales construites.',
                    'en' => '346 family latrines built.',
                ],
                'budget_amount' => 45550.00,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 250,
                'beneficiaries_unit' => 'personnes',
                'is_featured' => false,
                'published_at' => '2013-07-01 00:00:00',
                'partners' => [
                    'BETING' => 'implementer',
                ],
            ],
            [
                'slug' => 'route-numbi-ziralo',
                'domain' => 'logistique',
                'title' => [
                    'fr' => 'Réhabilitation de la route de 38 km Numbi – Ziralo (Kalehe)',
                    'en' => 'Rehabilitation of the 38 km Numbi – Ziralo road (Kalehe)',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Kalehe',
                'start_date' => '2014-01-01',
                'end_date' => '2014-12-01',
                'objectives' => [
                    'fr' => 'Faciliter l\'accès des humanitaires à la zone de santé de Minova.',
                    'en' => 'Facilitate humanitarian access to the Minova health zone.',
                ],
                'beneficiaries' => [
                    'fr' => '850 élèves',
                    'en' => '850 pupils',
                ],
                'results' => [
                    'fr' => '38 km de route réhabilités.',
                    'en' => '38 km of road rehabilitated.',
                ],
                'budget_amount' => 77850.00,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 850,
                'beneficiaries_unit' => 'élèves',
                'is_featured' => false,
                'published_at' => '2014-12-01 00:00:00',
                'partners' => [
                    'BETING' => 'implementer',
                ],
            ],
            [
                'slug' => 'autonomisation-jeunes-goma',
                'domain' => 'formation-professionnelle',
                'title' => [
                    'fr' => 'Autonomisation économique des jeunes à Goma',
                    'en' => 'Economic empowerment of young people in Goma',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Goma',
                'start_date' => '2017-01-01',
                'end_date' => '2017-12-01',
                'objectives' => [
                    'fr' => 'Former les jeunes et les accompagner vers l\'auto-emploi.',
                    'en' => 'Train young people and support them towards self-employment.',
                ],
                'beneficiaries' => [
                    'fr' => '300 jeunes',
                    'en' => '300 young people',
                ],
                'results' => [
                    'fr' => '300 jeunes formés à l\'entrepreneuriat.',
                    'en' => '300 young people trained in entrepreneurship.',
                ],
                'budget_amount' => 48994.00,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 300,
                'beneficiaries_unit' => 'jeunes',
                'is_featured' => false,
                'published_at' => '2017-12-01 00:00:00',
                'partners' => [
                    'UNICEF' => 'funder',
                ],
            ],
            [
                'slug' => 'pisciculture-tilapia-karhongo',
                'domain' => 'securite-alimentaire',
                'title' => [
                    'fr' => 'Production de poissons Tilapia en étangs piscicoles (Karhongo)',
                    'en' => 'Tilapia fish production in fish ponds (Karhongo)',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Karhongo, Walungu',
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-01',
                'objectives' => [
                    'fr' => 'Diversifier les sources de revenus et améliorer l\'alimentation des ménages.',
                    'en' => 'Diversify income sources and improve household nutrition.',
                ],
                'beneficiaries' => [
                    'fr' => '560 vendeuses de poissons',
                    'en' => '560 fish sellers',
                ],
                'results' => [
                    'fr' => 'Étangs piscicoles opérationnels et production de Tilapia lancée.',
                    'en' => 'Operational fish ponds and Tilapia production started.',
                ],
                'budget_amount' => 47983.10,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 560,
                'beneficiaries_unit' => 'vendeuses de poissons',
                'is_featured' => true,
                'published_at' => '2023-12-01 00:00:00',
                'partners' => [
                    'FAO' => 'funder',
                ],
            ],
            [
                'slug' => 'ecole-karhale-kadutu',
                'domain' => 'education',
                'title' => [
                    'fr' => 'Construction d\'une école primaire et secondaire à Karhale (Kadutu)',
                    'en' => 'Construction of a primary and secondary school in Karhale (Kadutu)',
                ],
                'status' => 'ongoing',
                'country' => 'RD Congo',
                'city' => 'Karhale, Kadutu',
                'start_date' => '2024-01-01',
                'end_date' => null,
                'objectives' => [
                    'fr' => 'Offrir un cadre scolaire adéquat aux enfants de la commune de Kadutu.',
                    'en' => 'Provide an adequate school environment for children in Kadutu commune.',
                ],
                'beneficiaries' => [
                    'fr' => '2 500 élèves',
                    'en' => '2,500 pupils',
                ],
                'results' => [
                    'fr' => 'École à deux niveaux et bâtiment communautaire en cours de construction.',
                    'en' => 'Two-level school and community building under construction.',
                ],
                'budget_amount' => 450000.00,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 2500,
                'beneficiaries_unit' => 'élèves',
                'is_featured' => false,
                'published_at' => '2024-01-15 00:00:00',
                'partners' => [
                    'BETING' => 'funder',
                ],
            ],
            [
                'slug' => 'jeunes-filles-meres-sake',
                'domain' => 'genre',
                'title' => [
                    'fr' => 'Appui et encadrement des jeunes filles mères à Saké (Nord-Kivu)',
                    'en' => 'Support and mentoring of young mothers in Sake (North Kivu)',
                ],
                'status' => 'ongoing',
                'country' => 'RD Congo',
                'city' => 'Saké, Masisi',
                'start_date' => '2024-01-01',
                'end_date' => null,
                'objectives' => [
                    'fr' => 'Accompagner les jeunes filles mères vers l\'autonomisation économique et sociale.',
                    'en' => 'Support young mothers towards economic and social empowerment.',
                ],
                'beneficiaries' => [
                    'fr' => '200 filles',
                    'en' => '200 girls',
                ],
                'results' => [
                    'fr' => 'Encadrement et appui aux jeunes filles mères en cours.',
                    'en' => 'Mentoring and support for young mothers in progress.',
                ],
                'budget_amount' => 80000.00,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 200,
                'beneficiaries_unit' => 'filles',
                'is_featured' => false,
                'published_at' => '2024-01-20 00:00:00',
                'partners' => [
                    'BETING' => 'funder',
                ],
            ],
            [
                'slug' => 'amenagement-des-8-territoires',
                'domain' => 'logistique',
                'title' => [
                    'fr' => 'Projet d\'aménagement des huit territoires',
                    'en' => 'Project for the development of the eight territories',
                ],
                'status' => 'awaiting_funding',
                'country' => 'RD Congo',
                'city' => 'Sud-Kivu et Nord-Kivu',
                'start_date' => null,
                'end_date' => null,
                'objectives' => [
                    'fr' => 'Réhabiliter les routes de desserte agricole, construire un barrage hydro-électrique et photovoltaïque, construire des micro-centrales et des centres d\'apprentissage de métiers dans les 8 territoires.',
                    'en' => 'Rehabilitate agricultural access roads, build a hydro-electric and photovoltaic dam, build micro-power plants and vocational training centres in the 8 territories.',
                ],
                'beneficiaries' => [
                    'fr' => '6 349 200 habitants',
                    'en' => '6,349,200 inhabitants',
                ],
                'results' => [
                    'fr' => 'Projet en attente de financement.',
                    'en' => 'Project awaiting funding.',
                ],
                'budget_amount' => 541591.00,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 6349200,
                'beneficiaries_unit' => 'habitants',
                'is_featured' => true,
                'published_at' => '2025-01-01 00:00:00',
                'partners' => [
                    'IPBS' => 'funder',
                    'NAMA Facility' => 'funder',
                ],
            ],
            [
                'slug' => 'cohabitation-femmes-burundaises',
                'domain' => 'protection',
                'title' => [
                    'fr' => 'Sensibilisation des femmes burundaises pour la cohabitation pacifique',
                    'en' => 'Awareness raising with Burundian women for peaceful coexistence',
                ],
                'status' => 'completed',
                'country' => 'Burundi',
                'city' => 'Bujumbura, Burundi',
                'start_date' => '1994-01-01',
                'end_date' => '1995-12-31',
                'objectives' => [
                    'fr' => 'Sensibiliser les femmes burundaises pour la cohabitation d\'ensemble entre femmes tutsi et femmes hutu.',
                    'en' => 'Raise awareness among Burundian women to foster coexistence between Tutsi and Hutu women.',
                ],
                'beneficiaries' => [
                    'fr' => '28 500 personnes',
                    'en' => '28,500 people',
                ],
                'results' => [
                    'fr' => 'Campagnes de sensibilisation menées au Burundi (37 500 $ en 1994 et 55 000 $ en 1995).',
                    'en' => 'Awareness campaigns carried out in Burundi (USD 37,500 in 1994 and USD 55,000 in 1995).',
                ],
                'budget_amount' => 92500.00,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 28500,
                'beneficiaries_unit' => 'personnes',
                'is_featured' => false,
                'published_at' => '1995-12-31 00:00:00',
                'partners' => [
                    'CECI' => 'funder',
                    'PNUD' => 'funder',
                ],
            ],
            [
                'slug' => 'atelier-couture-buyezi',
                'domain' => 'formation-professionnelle',
                'title' => [
                    'fr' => 'Installation d\'un atelier de couture à Buyezi',
                    'en' => 'Setting up a sewing workshop in Buyezi',
                ],
                'status' => 'completed',
                'country' => 'Burundi',
                'city' => 'Buyezi, Burundi',
                'start_date' => '1995-01-01',
                'end_date' => '1995-12-31',
                'objectives' => [
                    'fr' => 'Former les enfants orphelins et les veuves à la couture, à Buyezi et en ville.',
                    'en' => 'Train orphans and widows in sewing, in Buyezi and in the city.',
                ],
                'beneficiaries' => [
                    'fr' => '3 500 personnes et 500 élèves',
                    'en' => '3,500 people and 500 pupils',
                ],
                'results' => [
                    'fr' => 'Atelier de couture installé et formations dispensées (175 850 $ et 27 000 $).',
                    'en' => 'Sewing workshop set up and training delivered (USD 175,850 and USD 27,000).',
                ],
                'budget_amount' => 202850.00,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 4000,
                'beneficiaries_unit' => 'personnes',
                'is_featured' => false,
                'published_at' => '1995-12-31 00:00:00',
                'partners' => [
                    'AVEB' => 'implementer',
                ],
            ],
            [
                'slug' => 'ecole-orphelins-bujumbura',
                'domain' => 'education',
                'title' => [
                    'fr' => 'Construction d\'une école primaire pour les enfants orphelins à Bujumbura',
                    'en' => 'Construction of a primary school for orphans in Bujumbura',
                ],
                'status' => 'completed',
                'country' => 'Burundi',
                'city' => 'Bujumbura, Burundi',
                'start_date' => '1996-01-01',
                'end_date' => '1997-12-31',
                'objectives' => [
                    'fr' => 'Construire une école primaire pour la formation des enfants orphelins.',
                    'en' => 'Build a primary school to educate orphaned children.',
                ],
                'beneficiaries' => [
                    'fr' => '25 000 et 2 530 personnes',
                    'en' => '25,000 and 2,530 people',
                ],
                'results' => [
                    'fr' => 'École construite et mise en service (35 000 $ en 1996 et 100 000 $ en 1997).',
                    'en' => 'School built and operational (USD 35,000 in 1996 and USD 100,000 in 1997).',
                ],
                'budget_amount' => 135000.00,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 27530,
                'beneficiaries_unit' => 'personnes',
                'is_featured' => false,
                'published_at' => '1997-12-31 00:00:00',
            ],
            [
                'slug' => 'assainissement-site-uvira',
                'domain' => 'wash',
                'title' => [
                    'fr' => 'Assainissement du site d\'Uvira par l\'entretien des avenues',
                    'en' => 'Cleaning up the Uvira site through avenue maintenance',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Uvira',
                'start_date' => '1998-01-01',
                'end_date' => '1998-12-31',
                'objectives' => [
                    'fr' => 'Lutter contre l\'insalubrité par des travaux d\'entretien des avenues.',
                    'en' => 'Fight unsanitary conditions through avenue maintenance works.',
                ],
                'beneficiaries' => [
                    'fr' => '35 500 personnes',
                    'en' => '35,500 people',
                ],
                'results' => [
                    'fr' => 'Travaux d\'assainissement et d\'entretien des avenues réalisés.',
                    'en' => 'Cleaning and avenue maintenance works completed.',
                ],
                'budget_amount' => 210000.00,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 35500,
                'beneficiaries_unit' => 'personnes',
                'is_featured' => false,
                'published_at' => '1998-12-31 00:00:00',
            ],
            [
                'slug' => 'tuiles-briques-ruzizi',
                'domain' => 'formation-professionnelle',
                'title' => [
                    'fr' => 'Fabrication de tuiles, briques et foyers améliorés dans la plaine de la Ruzizi',
                    'en' => 'Production of tiles, bricks and improved stoves in the Ruzizi plain',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Plaine de la Ruzizi, Uvira',
                'start_date' => '1999-01-01',
                'end_date' => '1999-12-31',
                'objectives' => [
                    'fr' => 'Produire des tuiles, briques, foyers améliorés, carreaux et pots pour les ménages.',
                    'en' => 'Produce tiles, bricks, improved stoves, tiles and pots for households.',
                ],
                'beneficiaries' => [
                    'fr' => '54 800 personnes',
                    'en' => '54,800 people',
                ],
                'results' => [
                    'fr' => 'Production artisanale lancée dans la plaine de la Ruzizi.',
                    'en' => 'Artisanal production launched in the Ruzizi plain.',
                ],
                'budget_amount' => null,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 54800,
                'beneficiaries_unit' => 'personnes',
                'is_featured' => false,
                'published_at' => '1999-12-31 00:00:00',
                'partners' => [
                    'PAM' => 'funder',
                ],
            ],
            [
                'slug' => 'route-kamanyola-uvira',
                'domain' => 'logistique',
                'title' => [
                    'fr' => 'Réhabilitation de la route Kamanyola-Uvira',
                    'en' => 'Rehabilitation of the Kamanyola-Uvira road',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Uvira',
                'start_date' => '2000-01-01',
                'end_date' => '2000-12-31',
                'objectives' => [
                    'fr' => 'Réhabiliter la route Kamanyola-Uvira pour faciliter la mobilité des populations.',
                    'en' => 'Rehabilitate the Kamanyola-Uvira road to facilitate the movement of people.',
                ],
                'beneficiaries' => [
                    'fr' => '75 295 personnes',
                    'en' => '75,295 people',
                ],
                'results' => [
                    'fr' => 'Route réhabilitée et desserte améliorée.',
                    'en' => 'Road rehabilitated and access improved.',
                ],
                'budget_amount' => null,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 75295,
                'beneficiaries_unit' => 'personnes',
                'is_featured' => false,
                'published_at' => '2000-12-31 00:00:00',
            ],
            [
                'slug' => 'centres-sante-mazigiro-ibambiro',
                'domain' => 'sante',
                'title' => [
                    'fr' => 'Réhabilitation des centres de santé de Mazigiro et Ibambiro',
                    'en' => 'Rehabilitation of the Mazigiro and Ibambiro health centres',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Uvira',
                'start_date' => '2000-01-01',
                'end_date' => '2000-12-31',
                'objectives' => [
                    'fr' => 'Réhabiliter les deux centres de santé de Mazigiro et Ibambiro.',
                    'en' => 'Rehabilitate the two health centres of Mazigiro and Ibambiro.',
                ],
                'beneficiaries' => [
                    'fr' => '12 500 personnes',
                    'en' => '12,500 people',
                ],
                'results' => [
                    'fr' => 'Centres de santé réhabilités et opérationnels.',
                    'en' => 'Health centres rehabilitated and operational.',
                ],
                'budget_amount' => null,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 12500,
                'beneficiaries_unit' => 'personnes',
                'is_featured' => false,
                'published_at' => '2000-12-31 00:00:00',
                'partners' => [
                    'PAM' => 'funder',
                    'USAID' => 'funder',
                ],
            ],
            [
                'slug' => 'centres-sante-walungu',
                'domain' => 'sante',
                'title' => [
                    'fr' => 'Construction et réhabilitation de centres de santé à Walungu',
                    'en' => 'Construction and rehabilitation of health centres in Walungu',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Walungu',
                'start_date' => '2005-01-01',
                'end_date' => '2006-12-31',
                'objectives' => [
                    'fr' => 'Construire deux centres de santé, réhabiliter 17 autres et réaliser 12 latrines publiques et 4 blocs de douches pour la protection de la santé maternelle et infantile.',
                    'en' => 'Build two health centres, rehabilitate 17 more and build 12 public latrines and 4 shower blocks for maternal and child health protection.',
                ],
                'beneficiaries' => [
                    'fr' => '12 250 personnes',
                    'en' => '12,250 people',
                ],
                'results' => [
                    'fr' => 'Infrastructures sanitaires et d\'hygiène construites et réhabilitées à Walungu.',
                    'en' => 'Health and hygiene facilities built and rehabilitated in Walungu.',
                ],
                'budget_amount' => null,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 12250,
                'beneficiaries_unit' => 'personnes',
                'is_featured' => false,
                'published_at' => '2006-12-31 00:00:00',
            ],
            [
                'slug' => 'escalier-bukavu',
                'domain' => 'logistique',
                'title' => [
                    'fr' => 'Construction d\'un escalier de 5 400 mètres à Bukavu',
                    'en' => 'Construction of a 5,400-metre staircase in Bukavu',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Bukavu',
                'start_date' => '2006-01-01',
                'end_date' => '2006-12-31',
                'objectives' => [
                    'fr' => 'Construire un escalier de 5 400 mètres à Bukavu dans le cadre de l\'assainissement et du renforcement de la cohabitation pacifique.',
                    'en' => 'Build a 5,400-metre staircase in Bukavu as part of sanitation and the strengthening of peaceful coexistence.',
                ],
                'beneficiaries' => [
                    'fr' => 'Communauté de Bukavu',
                    'en' => 'Bukavu community',
                ],
                'results' => [
                    'fr' => 'Escalier construit (24 500 $, 50 000 $ et 18 000 $).',
                    'en' => 'Staircase built (USD 24,500, USD 50,000 and USD 18,000).',
                ],
                'budget_amount' => 92500.00,
                'budget_currency' => 'USD',
                'beneficiaries_count' => null,
                'beneficiaries_unit' => 'personnes',
                'is_featured' => false,
                'published_at' => '2006-12-31 00:00:00',
                'partners' => [
                    'MONUC' => 'funder',
                ],
            ],
            [
                'slug' => 'petits-betails-lemera',
                'domain' => 'securite-alimentaire',
                'title' => [
                    'fr' => 'Distribution de petits bétails aux femmes retournées de Lemera',
                    'en' => 'Distribution of small livestock to returning women in Lemera',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Lemera, Sud-Kivu',
                'start_date' => '2006-01-01',
                'end_date' => '2006-12-31',
                'objectives' => [
                    'fr' => 'Assurer la prise en charge des femmes en situation post-conflit et contribuer à leur autonomisation et à la lutte contre la pauvreté dans les ménages retournés.',
                    'en' => 'Support women in post-conflict situations and contribute to their empowerment and to the fight against poverty in returning households.',
                ],
                'beneficiaries' => [
                    'fr' => 'Femmes retournées du moyen plateau de Lemera',
                    'en' => 'Returning women from the middle plateau of Lemera',
                ],
                'results' => [
                    'fr' => 'Petits bétails distribués aux femmes retournées (12 500 $ et 180 000 $).',
                    'en' => 'Small livestock distributed to returning women (USD 12,500 and USD 180,000).',
                ],
                'budget_amount' => 192500.00,
                'budget_currency' => 'USD',
                'beneficiaries_count' => null,
                'beneficiaries_unit' => 'personnes',
                'is_featured' => false,
                'published_at' => '2006-12-31 00:00:00',
                'partners' => [
                    'BDOM' => 'funder',
                    'Louvain Développement' => 'funder',
                ],
            ],
            [
                'slug' => 'maternite-kasenga',
                'domain' => 'sante',
                'title' => [
                    'fr' => 'Réhabilitation de la maternité de Kasenga',
                    'en' => 'Rehabilitation of the Kasenga maternity unit',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Kasenga',
                'start_date' => '2006-01-01',
                'end_date' => '2006-12-31',
                'objectives' => [
                    'fr' => 'Réhabiliter la maternité de Kasenga dans le cadre de l\'autonomisation et de l\'assistance des femmes en post-partum.',
                    'en' => 'Rehabilitate the Kasenga maternity unit to support and empower women in the post-partum period.',
                ],
                'beneficiaries' => [
                    'fr' => 'Femmes en post-partum',
                    'en' => 'Post-partum women',
                ],
                'results' => [
                    'fr' => 'Maternité réhabilitée.',
                    'en' => 'Maternity unit rehabilitated.',
                ],
                'budget_amount' => null,
                'budget_currency' => 'USD',
                'beneficiaries_count' => null,
                'beneficiaries_unit' => 'personnes',
                'is_featured' => false,
                'published_at' => '2006-12-31 00:00:00',
            ],
            [
                'slug' => 'ecoles-fizi-50-classes',
                'domain' => 'education',
                'title' => [
                    'fr' => 'Réhabilitation de 50 classes dans les écoles de Fizi',
                    'en' => 'Rehabilitation of 50 classrooms in the schools of Fizi',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Fizi',
                'start_date' => '2006-01-01',
                'end_date' => '2006-12-31',
                'objectives' => [
                    'fr' => 'Réhabiliter 50 classes dans les écoles de Fizi pour soutenir la scolarisation « toutes les filles à l\'école ».',
                    'en' => 'Rehabilitate 50 classrooms in the schools of Fizi to support the "all girls in school" initiative.',
                ],
                'beneficiaries' => [
                    'fr' => 'Élèves des écoles de Fizi',
                    'en' => 'Pupils of the schools of Fizi',
                ],
                'results' => [
                    'fr' => '50 classes réhabilitées dans les écoles de Fizi.',
                    'en' => '50 classrooms rehabilitated in the schools of Fizi.',
                ],
                'budget_amount' => null,
                'budget_currency' => 'USD',
                'beneficiaries_count' => null,
                'beneficiaries_unit' => 'élèves',
                'is_featured' => false,
                'published_at' => '2006-12-31 00:00:00',
                'partners' => [
                    'SPES' => 'funder',
                    'HCR' => 'funder',
                ],
            ],
            [
                'slug' => 'ecoles-latrines-citernes-ruzizi',
                'domain' => 'education',
                'title' => [
                    'fr' => 'Construction de 4 écoles, latrines et citernes dans la plaine de la Ruzizi',
                    'en' => 'Construction of 4 schools, latrines and water tanks in the Ruzizi plain',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Plaine de la Ruzizi, Uvira',
                'start_date' => '2006-01-01',
                'end_date' => '2006-12-31',
                'objectives' => [
                    'fr' => 'Construire 4 écoles, 18 latrines publiques de 6 portes et 19 citernes de 1 m³ pour assainir les lieux scolaires et lutter contre les maladies d\'origine hydrique.',
                    'en' => 'Build 4 schools, 18 public latrines with 6 doors and 19 one-cubic-metre water tanks to sanitise school premises and fight waterborne diseases.',
                ],
                'beneficiaries' => [
                    'fr' => 'Élèves de la plaine de la Ruzizi',
                    'en' => 'Pupils of the Ruzizi plain',
                ],
                'results' => [
                    'fr' => 'Écoles, latrines publiques et citernes construites.',
                    'en' => 'Schools, public latrines and water tanks built.',
                ],
                'budget_amount' => null,
                'budget_currency' => 'USD',
                'beneficiaries_count' => null,
                'beneficiaries_unit' => 'élèves',
                'is_featured' => false,
                'published_at' => '2006-12-31 00:00:00',
                'partners' => [
                    'AVSI' => 'funder',
                    'ECHO' => 'funder',
                    'UNICEF' => 'funder',
                ],
            ],
            [
                'slug' => 'encadrement-jeunes-beni',
                'domain' => 'protection',
                'title' => [
                    'fr' => 'Appui à l\'encadrement des jeunes déplacés et retournés à Beni',
                    'en' => 'Support for mentoring displaced and returning youth in Beni',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Beni, Nord-Kivu',
                'start_date' => '2010-01-01',
                'end_date' => '2013-12-31',
                'objectives' => [
                    'fr' => 'Encadrer les jeunes déplacés, retournés et défavorisés de Beni (Nord-Kivu) pour leur réinsertion socio-économique.',
                    'en' => 'Mentor displaced, returning and underprivileged youth in Beni (North Kivu) for their socio-economic reintegration.',
                ],
                'beneficiaries' => [
                    'fr' => '21 590 personnes et 250 filles et garçons',
                    'en' => '21,590 people and 250 girls and boys',
                ],
                'results' => [
                    'fr' => 'Jeunes déplacés et retournés encadrés (114 055 $ et 45 550 $).',
                    'en' => 'Displaced and returning youth mentored (USD 114,055 and USD 45,550).',
                ],
                'budget_amount' => 159605.00,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 21840,
                'beneficiaries_unit' => 'personnes',
                'is_featured' => false,
                'published_at' => '2013-12-31 00:00:00',
                'partners' => [
                    'BARAKA' => 'funder',
                ],
            ],
            [
                'slug' => 'rehabilitation-ep-bakhita',
                'domain' => 'education',
                'title' => [
                    'fr' => 'Réhabilitation de l\'école primaire Bakhita',
                    'en' => 'Rehabilitation of Bakhita primary school',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => null,
                'start_date' => '2021-01-01',
                'end_date' => '2022-12-31',
                'objectives' => [
                    'fr' => 'Réhabiliter 12 classes de l\'EP Bakhita, installer des latrines de 4 portes et sensibiliser à l\'hygiène et à l\'assainissement.',
                    'en' => 'Rehabilitate 12 classrooms at Bakhita primary school, install 4-door latrines and raise awareness on hygiene and sanitation.',
                ],
                'beneficiaries' => [
                    'fr' => '2 200 élèves et 1 360 ménages riziculteurs',
                    'en' => '2,200 pupils and 1,360 rice-farming households',
                ],
                'results' => [
                    'fr' => 'École réhabilitée et latrines installées.',
                    'en' => 'School rehabilitated and latrines installed.',
                ],
                'budget_amount' => null,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 2200,
                'beneficiaries_unit' => 'élèves',
                'is_featured' => false,
                'published_at' => '2022-12-31 00:00:00',
                'partners' => [
                    'EDAP' => 'funder',
                    'PICAG' => 'funder',
                ],
            ],
            [
                'slug' => 'entreprenariat-jeunes-masisi',
                'domain' => 'formation-professionnelle',
                'title' => [
                    'fr' => 'Formation à l\'entrepreneuriat des jeunes de Masisi',
                    'en' => 'Entrepreneurship training for youth in Masisi',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Masisi, Nord-Kivu',
                'start_date' => '2021-01-01',
                'end_date' => '2022-12-31',
                'objectives' => [
                    'fr' => 'Former les jeunes filles et garçons de Masisi à l\'entrepreneuriat.',
                    'en' => 'Train girls and boys in Masisi in entrepreneurship.',
                ],
                'beneficiaries' => [
                    'fr' => 'Jeunes filles et garçons de Masisi',
                    'en' => 'Girls and boys of Masisi',
                ],
                'results' => [
                    'fr' => 'Formations à l\'entrepreneuriat dispensées.',
                    'en' => 'Entrepreneurship training delivered.',
                ],
                'budget_amount' => null,
                'budget_currency' => 'USD',
                'beneficiaries_count' => null,
                'beneficiaries_unit' => 'jeunes',
                'is_featured' => false,
                'published_at' => '2022-12-31 00:00:00',
            ],
            [
                'slug' => 'citernes-ep-camp-saio',
                'domain' => 'wash',
                'title' => [
                    'fr' => 'Installation de citernes à l\'école primaire Camp SAIO',
                    'en' => 'Installation of water tanks at Camp SAIO primary school',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => null,
                'start_date' => '2022-01-01',
                'end_date' => '2022-12-31',
                'objectives' => [
                    'fr' => 'Installer des citernes à l\'eau à l\'EP Camp SAIO pour lutter contre le choléra et les maladies hydriques en milieu scolaire et construire la logette du groupe électrogène à la division provinciale de la jeunesse.',
                    'en' => 'Install water tanks at Camp SAIO school to fight cholera and waterborne diseases in schools and build the generator housing at the provincial youth division.',
                ],
                'beneficiaries' => [
                    'fr' => 'Élèves de l\'école Camp SAIO',
                    'en' => 'Pupils of Camp SAIO school',
                ],
                'results' => [
                    'fr' => 'Citernes installées et logette du groupe électrogène construite.',
                    'en' => 'Water tanks installed and generator housing built.',
                ],
                'budget_amount' => null,
                'budget_currency' => 'USD',
                'beneficiaries_count' => null,
                'beneficiaries_unit' => 'élèves',
                'is_featured' => false,
                'published_at' => '2022-12-31 00:00:00',
            ],
            [
                'slug' => 'formation-jeunes-nyiragongo',
                'domain' => 'formation-professionnelle',
                'title' => [
                    'fr' => 'Formation des jeunes pour la lutte contre la pauvreté à Nyiragongo',
                    'en' => 'Youth training to fight poverty in Nyiragongo',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Nyiragongo, Nord-Kivu',
                'start_date' => '2022-01-01',
                'end_date' => '2022-12-31',
                'objectives' => [
                    'fr' => 'Former les jeunes de Nyiragongo pour la lutte contre la pauvreté.',
                    'en' => 'Train young people in Nyiragongo in the fight against poverty.',
                ],
                'beneficiaries' => [
                    'fr' => 'Jeunes de Nyiragongo',
                    'en' => 'Youth of Nyiragongo',
                ],
                'results' => [
                    'fr' => 'Formations professionnelles dispensées.',
                    'en' => 'Vocational training delivered.',
                ],
                'budget_amount' => null,
                'budget_currency' => 'USD',
                'beneficiaries_count' => null,
                'beneficiaries_unit' => 'jeunes',
                'is_featured' => false,
                'published_at' => '2022-12-31 00:00:00',
            ],
            [
                'slug' => 'construction-rehabilitation-ep-edap-isp',
                'domain' => 'education',
                'title' => [
                    'fr' => 'Construction et réhabilitation de l\'EP EDAP/ISP',
                    'en' => 'Construction and rehabilitation of the EDAP/ISP primary school',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => null,
                'start_date' => '2022-01-01',
                'end_date' => '2022-12-31',
                'objectives' => [
                    'fr' => 'Construire et réhabiliter l\'école primaire EDAP/ISP.',
                    'en' => 'Build and rehabilitate the EDAP/ISP primary school.',
                ],
                'beneficiaries' => [
                    'fr' => 'Élèves de l\'EP EDAP/ISP',
                    'en' => 'Pupils of EDAP/ISP primary school',
                ],
                'results' => [
                    'fr' => 'École construite et réhabilitée.',
                    'en' => 'School built and rehabilitated.',
                ],
                'budget_amount' => null,
                'budget_currency' => 'USD',
                'beneficiaries_count' => null,
                'beneficiaries_unit' => 'élèves',
                'is_featured' => false,
                'published_at' => '2022-12-31 00:00:00',
            ],
            [
                'slug' => 'entrepot-riz-nyamubanda',
                'domain' => 'securite-alimentaire',
                'title' => [
                    'fr' => 'Construction d\'un entrepôt de riz à Karhongo (Nyangezi)',
                    'en' => 'Construction of a rice warehouse in Karhongo (Nyangezi)',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Karhongo, Walungu',
                'start_date' => '2022-01-01',
                'end_date' => '2022-12-31',
                'objectives' => [
                    'fr' => 'Construire un entrepôt de stockage du riz au profit des riziculteurs des marais Nyamubanda et Hogola.',
                    'en' => 'Build a rice storage warehouse for the rice farmers of the Nyamubanda and Hogola marshes.',
                ],
                'beneficiaries' => [
                    'fr' => 'Riziculteurs du marais Nyamubanda et Hogola',
                    'en' => 'Rice farmers of the Nyamubanda and Hogola marshes',
                ],
                'results' => [
                    'fr' => 'Entrepôt de stockage construit.',
                    'en' => 'Storage warehouse built.',
                ],
                'budget_amount' => null,
                'budget_currency' => 'USD',
                'beneficiaries_count' => null,
                'beneficiaries_unit' => 'ménages',
                'is_featured' => false,
                'published_at' => '2022-12-31 00:00:00',
            ],
            [
                'slug' => 'sensibilisation-ebola-covid19',
                'domain' => 'sante',
                'title' => [
                    'fr' => 'Sensibilisation contre Ebola, la COVID-19 et l\'IPOX en milieux scolaires',
                    'en' => 'Awareness raising on Ebola, COVID-19 and MPOX in schools',
                ],
                'status' => 'completed',
                'country' => 'RD Congo',
                'city' => 'Sud-Kivu',
                'start_date' => '2018-01-01',
                'end_date' => '2022-12-31',
                'objectives' => [
                    'fr' => 'Sensibiliser sur les mesures de prévention et la communication sur la maladie à virus Ebola, la COVID-19 et l\'IPOX en milieux scolaires dans les zones de santé à haut risque de la province du Sud-Kivu.',
                    'en' => 'Raise awareness on prevention measures and communication on Ebola, COVID-19 and MPOX in schools in high-risk health zones of South Kivu province.',
                ],
                'beneficiaries' => [
                    'fr' => '60 écoles primaires et 30 écoles secondaires',
                    'en' => '60 primary schools and 30 secondary schools',
                ],
                'results' => [
                    'fr' => 'Campagnes de sensibilisation menées dans les zones à haut risque.',
                    'en' => 'Awareness campaigns carried out in high-risk zones.',
                ],
                'budget_amount' => null,
                'budget_currency' => 'USD',
                'beneficiaries_count' => null,
                'beneficiaries_unit' => 'écoles',
                'is_featured' => false,
                'published_at' => '2022-12-31 00:00:00',
                'partners' => [
                    'EPSP' => 'funder',
                    'UNICEF' => 'funder',
                ],
            ],
            [
                'slug' => 'barrage-hydro-electrique-8-territoires',
                'domain' => 'logistique',
                'title' => [
                    'fr' => 'Construction d\'un barrage hydro-électrique et photovoltaïque',
                    'en' => 'Construction of a hydro-electric and photovoltaic dam',
                ],
                'status' => 'awaiting_funding',
                'country' => 'RD Congo',
                'city' => 'Sud-Kivu et Nord-Kivu',
                'start_date' => null,
                'end_date' => null,
                'objectives' => [
                    'fr' => 'Construire un barrage hydro-électrique et un barrage photovoltaïque pour l\'alimentation durable en énergie des 8 territoires.',
                    'en' => 'Build a hydro-electric dam and a photovoltaic dam for sustainable energy supply across the 8 territories.',
                ],
                'beneficiaries' => [
                    'fr' => '3 000 ménages',
                    'en' => '3,000 households',
                ],
                'results' => [
                    'fr' => 'Projet en attente de financement.',
                    'en' => 'Project awaiting funding.',
                ],
                'budget_amount' => 365240.00,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 3000,
                'beneficiaries_unit' => 'ménages',
                'is_featured' => false,
                'published_at' => '2024-12-15 00:00:00',
                'partners' => [
                    'IPBS' => 'funder',
                    'NAMA Facility' => 'funder',
                ],
            ],
            [
                'slug' => 'micro-centrales-hydro-8-territoires',
                'domain' => 'logistique',
                'title' => [
                    'fr' => 'Construction des micro-centrales hydro-électriques dans les 8 territoires',
                    'en' => 'Construction of micro hydro-electric power plants in the 8 territories',
                ],
                'status' => 'awaiting_funding',
                'country' => 'RD Congo',
                'city' => 'Sud-Kivu et Nord-Kivu',
                'start_date' => null,
                'end_date' => null,
                'objectives' => [
                    'fr' => 'Construire des micro-centrales hydro-électriques dans les 8 territoires.',
                    'en' => 'Build micro hydro-electric power plants in the 8 territories.',
                ],
                'beneficiaries' => [
                    'fr' => '6 000 ménages',
                    'en' => '6,000 households',
                ],
                'results' => [
                    'fr' => 'Projet en attente de financement.',
                    'en' => 'Project awaiting funding.',
                ],
                'budget_amount' => null,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 6000,
                'beneficiaries_unit' => 'ménages',
                'is_featured' => false,
                'published_at' => '2024-12-15 00:00:00',
                'partners' => [
                    'IPBS' => 'funder',
                    'NAMA Facility' => 'funder',
                ],
            ],
            [
                'slug' => 'securite-alimentaire-riz-fizi',
                'domain' => 'securite-alimentaire',
                'title' => [
                    'fr' => 'Relance de la production du riz à Fizi',
                    'en' => 'Reviving rice production in Fizi',
                ],
                'status' => 'awaiting_funding',
                'country' => 'RD Congo',
                'city' => 'Fizi',
                'start_date' => null,
                'end_date' => null,
                'objectives' => [
                    'fr' => 'Relancer la production du riz dans le territoire de Fizi pour une sécurité alimentaire durable.',
                    'en' => 'Revive rice production in the Fizi territory for sustainable food security.',
                ],
                'beneficiaries' => [
                    'fr' => '900 ménages',
                    'en' => '900 households',
                ],
                'results' => [
                    'fr' => 'Projet en attente de financement.',
                    'en' => 'Project awaiting funding.',
                ],
                'budget_amount' => 257345.00,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 900,
                'beneficiaries_unit' => 'ménages',
                'is_featured' => false,
                'published_at' => '2024-12-15 00:00:00',
            ],
            [
                'slug' => 'integration-genre-femmes-sud-kivu',
                'domain' => 'genre',
                'title' => [
                    'fr' => 'Développement communautaire au profit des femmes du Sud-Kivu',
                    'en' => 'Community development for women in South Kivu',
                ],
                'status' => 'awaiting_funding',
                'country' => 'RD Congo',
                'city' => 'Sud-Kivu',
                'start_date' => null,
                'end_date' => null,
                'objectives' => [
                    'fr' => 'Développer des activités génératrices de revenus au profit des femmes sur l\'ensemble de la province du Sud-Kivu (projet d\'intégration du genre).',
                    'en' => 'Develop income-generating activities for women across the whole province of South Kivu (gender integration project).',
                ],
                'beneficiaries' => [
                    'fr' => '456 000 personnes',
                    'en' => '456,000 people',
                ],
                'results' => [
                    'fr' => 'Projet en attente de financement.',
                    'en' => 'Project awaiting funding.',
                ],
                'budget_amount' => 2261475.00,
                'budget_currency' => 'USD',
                'beneficiaries_count' => 456000,
                'beneficiaries_unit' => 'personnes',
                'is_featured' => false,
                'published_at' => '2024-12-15 00:00:00',
                'partners' => [
                    'ATUNGA FIZI' => 'funder',
                ],
            ],
            [
                'slug' => 'drainage-marais-nyamubanda',
                'domain' => 'securite-alimentaire',
                'title' => [
                    'fr' => 'Drainage complet du marais Nyamubanda',
                    'en' => 'Complete drainage of the Nyamubanda marsh',
                ],
                'status' => 'awaiting_funding',
                'country' => 'RD Congo',
                'city' => 'Karhongo, Walungu',
                'start_date' => null,
                'end_date' => null,
                'objectives' => [
                    'fr' => 'Améliorer la production agricole grâce au drainage complet du marais Nyamubanda dans le groupement de Karhongo/Nyangezi, territoire de Walungu.',
                    'en' => 'Improve agricultural production through the complete drainage of the Nyamubanda marsh in the Karhongo/Nyangezi grouping, Walungu territory.',
                ],
                'beneficiaries' => [
                    'fr' => 'Ménages agricoles de Karhongo',
                    'en' => 'Farming households of Karhongo',
                ],
                'results' => [
                    'fr' => 'Projet en attente de financement.',
                    'en' => 'Project awaiting funding.',
                ],
                'budget_amount' => null,
                'budget_currency' => 'USD',
                'beneficiaries_count' => null,
                'beneficiaries_unit' => 'ménages',
                'is_featured' => false,
                'published_at' => '2024-12-15 00:00:00',
            ],
            [
                'slug' => 'relance-production-agricole-fizi',
                'domain' => 'securite-alimentaire',
                'title' => [
                    'fr' => 'Relance de la production agricole à Fizi',
                    'en' => 'Reviving agricultural production in Fizi',
                ],
                'status' => 'awaiting_funding',
                'country' => 'RD Congo',
                'city' => 'Fizi',
                'start_date' => null,
                'end_date' => null,
                'objectives' => [
                    'fr' => 'Relancer la production agricole à Fizi pour une sécurité alimentaire durable.',
                    'en' => 'Revive agricultural production in Fizi for sustainable food security.',
                ],
                'beneficiaries' => [
                    'fr' => 'Ménages agricoles de Fizi',
                    'en' => 'Farming households of Fizi',
                ],
                'results' => [
                    'fr' => 'Projet en attente de financement.',
                    'en' => 'Project awaiting funding.',
                ],
                'budget_amount' => null,
                'budget_currency' => 'USD',
                'beneficiaries_count' => null,
                'beneficiaries_unit' => 'ménages',
                'is_featured' => false,
                'published_at' => '2024-12-15 00:00:00',
            ],
        ];
        foreach ($projects as $data) {
            $domain = Domain::where('slug', $data['domain'])->firstOrFail();
            $partners = $data['partners'] ?? [];

            unset($data['domain'], $data['partners']);

            $project = Project::updateOrCreate(
                ['slug' => $data['slug']],
                array_merge($data, ['domain_id' => $domain->id])
            );

            foreach ($partners as $partnerName => $role) {
                $partner = Partner::where('name', $partnerName)->firstOrFail();

                $project->partners()->syncWithoutDetaching([$partner->id => ['role' => $role]]);
            }
        }

    }
}
